-- CatchThePrice canonical database baseline notice
--
-- This file is intentionally NON-EXECUTABLE.
-- The old monolithic bootstrap schema was retired because it no longer matched
-- the production Supabase database and contained obsolete assumptions.
--
-- Production database evolution is tracked only through:
--   supabase/migrations/
--
-- Before changing the database:
-- 1. inspect the current production schema,
-- 2. create a new migration under supabase/migrations/,
-- 3. apply it through the approved Supabase migration workflow,
-- 4. verify RLS, indexes and server-only access assumptions,
-- 5. update docs/CATCHTHEPRICE_MASTER_EXECUTION.md when launch behavior changes.
--
-- Do not rebuild production from a historical snapshot. Generate a fresh
-- canonical baseline from the verified production database only if/when the
-- project formally adopts a baseline/squash migration process.
