'use client';

import React from 'react';
import { Globe, CheckCircle2, Code2, ExternalLink } from 'lucide-react';

export default function AdminSeoPage() {
  const seoRoutes = [
    {
      route: '/ae/product/iphone-16-pro-max-256gb',
      title: 'Apple iPhone 16 Pro Max (256GB, Desert Titanium) — Best Price & Drops in UAE',
      schema: 'Product, AggregateOffer, BreadcrumbList',
      status: 'Indexed & Valid',
    },
    {
      route: '/us/product/playstation-5-pro-2tb',
      title: 'Sony PlayStation 5 Pro Console (2TB SSD, PSSR AI Upscaling) — Best Price in USA',
      schema: 'Product, AggregateOffer, BreadcrumbList',
      status: 'Indexed & Valid',
    },
    {
      route: '/ae/deals/phones',
      title: 'Best Phones Deals in UAE — CatchThePrice',
      schema: 'CollectionPage, ItemList',
      status: 'Indexed & Valid',
    },
    {
      route: '/us/price-drops/laptops',
      title: 'Biggest Laptops Price Drops in USA — CatchThePrice',
      schema: 'CollectionPage, ItemList',
      status: 'Indexed & Valid',
    },
    {
      route: '/sitemap.xml',
      title: 'CatchThePrice Dynamic XML Sitemap',
      schema: 'XML Sitemap v0.9',
      status: 'Dynamic Autogenerated',
    },
    {
      route: '/robots.txt',
      title: 'CatchThePrice Robots Specification',
      schema: 'Standard Disallow /api, Allow public routes',
      status: 'Active',
    },
  ];

  return (
    <div className="space-y-6">
      <div className="pb-6 border-b border-ctp">
        <h1 className="text-2xl font-extrabold text-slate-100">SEO &amp; Structured Data Engine</h1>
        <p className="text-xs text-slate-400 mt-1">
          Monitor canonical indexing, OpenGraph cards, hreflang tags, and Schema.org rich snippets
        </p>
      </div>

      <div className="rounded-2xl bg-ctp-surface border border-ctp overflow-hidden">
        <div className="p-4 border-b border-ctp flex items-center justify-between">
          <h3 className="font-bold text-sm text-slate-200">Core High-Authority Routes</h3>
          <span className="text-xs text-emerald-400 font-semibold">100% Schema Validated</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300">
            <thead className="bg-ctp-surface-elevated text-slate-400 uppercase tracking-wider text-[10px] border-b border-ctp">
              <tr>
                <th className="p-3.5">Route</th>
                <th className="p-3.5">Target Meta Title</th>
                <th className="p-3.5">Schema.org Types</th>
                <th className="p-3.5">Status</th>
                <th className="p-3.5 text-right">View</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-ctp">
              {seoRoutes.map((r, i) => (
                <tr key={i} className="hover:bg-slate-800/40 transition-colors">
                  <td className="p-3.5 font-mono text-emerald-400 font-medium">{r.route}</td>
                  <td className="p-3.5 text-slate-200 max-w-sm truncate">{r.title}</td>
                  <td className="p-3.5 text-slate-400">{r.schema}</td>
                  <td className="p-3.5">
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
                      {r.status}
                    </span>
                  </td>
                  <td className="p-3.5 text-right">
                    <a
                      href={r.route}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-emerald-400 hover:text-emerald-300 inline-flex items-center gap-1 font-semibold"
                    >
                      <span>Open</span>
                      <ExternalLink className="w-3 h-3" />
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
