'use client';
import React from 'react';
import { Product } from '@/lib/types';
import { useCountry } from '@/context/CountryContext';
import { Bookmark, Store } from 'lucide-react';
interface ProductCardProps { product: Product; priority?: boolean; priceContext?: 'reference'|'previous_observation'; }
function previousObservedPrice(product:Product):number|null{const h=[...(product.priceHistory||[])].filter(p=>Number.isFinite(p.price)&&p.price>0).sort((a,b)=>a.date.localeCompare(b.date));if(h.length<2)return null;const p=h[h.length-2].price,l=h[h.length-1].price;return l<p?p:null;}
export function ProductCard({product,priority=false,priceContext='reference'}:ProductCardProps){const {country,formatLocalPrice,toggleSaveProduct,isProductSaved}=useCountry();const saved=isProductSaved(product.id);const prev=priceContext==='previous_observation'?previousObservedPrice(product):null;const base=prev||product.originalPrice;const discount=base>product.currentBestPrice?Math.round(((base-product.currentBestPrice)/base)*100):0;return <div className="group relative bg-white border border-[#e0e4e2] hover:border-[#a9c9bb] hover:shadow-[0_7px_20px_rgba(25,55,45,.08)] transition-all flex flex-col overflow-hidden rounded-[7px]">
<div className="relative w-full pt-[72%] bg-white overflow-hidden"><a href={`/${country}/product/${product.slug}`} className="absolute inset-0 p-3 flex items-center justify-center"><img src={product.imageUrl} alt={product.title} loading={priority?'eager':'lazy'} className="max-h-full max-w-full object-contain group-hover:scale-[1.03] transition-transform"/></a>{discount>0&&<div className="absolute top-2 left-2 px-2 py-1 rounded-[4px] text-[9px] font-black bg-[#d92727] text-white">-{discount}%</div>}<button type="button" onClick={e=>{e.preventDefault();e.stopPropagation();toggleSaveProduct(product.id)}} className={`absolute top-2 right-2 w-8 h-8 rounded-full flex items-center justify-center border shadow-sm ${saved?'bg-[#087f4e] text-white border-[#087f4e]':'bg-white text-[#66767b] border-[#e0e4e2]'}`} aria-label={saved?'Remove from saved':'Save product'}><Bookmark className={`w-3.5 h-3.5 ${saved?'fill-current':''}`}/></button></div>
<div className="p-3 flex-1 flex flex-col"><div className="text-[9px] uppercase tracking-[.08em] font-bold text-[#77857f]">{product.brand}</div><a href={`/${country}/product/${product.slug}`} className="mt-1 text-[11px] sm:text-[12px] font-bold leading-[1.35] text-[#17262c] line-clamp-2 min-h-[32px] group-hover:text-[#08784b]">{product.title}</a><div className="mt-auto pt-3"><div className="text-[9px] text-[#87938e]">From</div><div className="mt-0.5 flex items-baseline gap-1.5 flex-wrap"><span className="text-[15px] sm:text-[17px] font-black text-[#111f24]">{formatLocalPrice(product.currentBestPrice)}</span>{base>product.currentBestPrice&&<span className="text-[9px] text-[#9aa4a0] line-through">{formatLocalPrice(base)}</span>}</div><div className="mt-2 flex items-center justify-between gap-2"><span className="inline-flex items-center gap-1 text-[9px] text-[#697873]"><Store className="w-3 h-3 text-[#08784b]"/>{product.offersCount} store{product.offersCount===1?'':'s'}</span><a href={`/${country}/product/${product.slug}`} className="text-[9px] font-black text-[#08784b]">COMPARE ›</a></div></div></div></div>}
